# Generated by Django 4.1 on 2022-08-27 14:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TR')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('Prefer', 'Prefer not to say')], max_length=50)),
                ('path', models.CharField(choices=[('FS', 'FullStack'), ('FE', 'Front-End'), ('BE', 'Back-End')], max_length=50)),
            ],
        ),
    ]
