# Generated by Django 4.1 on 2022-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='path',
            field=models.CharField(choices=[('FullStack', 'FullStack'), ('Front-End', 'Front-End'), ('Back-End', 'Back-End')], max_length=50),
        ),
    ]
